name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install operating system dependencies
        run: |
          npm install -g allure-commandline --save-dev 

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Robot Framework tests
        run: robot --listener allure_robotframework --prerunmodifier allure_robotframework.testplan robotframework/tests/

      # - name: 📊 Collect Allure files and generate allure-report folder
      #   run: |
      #     allure generate ./output/allure -o allure-results/
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: ./output/allure
          allure_results: allure-results

      - name: 🎁 Publishing Allure artifact to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: my_reports
          path: my_reports
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: allure-results
          # destination_dir: allure-results
      
      