name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install webdriver-manager

      - name: Run Robot Framework tests
        working-directory: ./robotframework
        run: robot -d reports tests/

      - name: Rename report.html to index.html
        run: |
          cp robotframework/reports/report.html robotframework/reports/index.html

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./robotframework/reports
          publish_branch: gh-pages