name: Robot Framework
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check working directory
        run: pwd

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip

      - name: Install Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
        
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '139.0.7258.68'  # Sesuaikan versi jika perlu
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable
        
      - name: Check Chrome Version
        run: google-chrome-stable --version

      - name: Check ChromeDriver Version
        run: chromedriver --version

      - name: Set permissions for the reports directory
        run: chmod -R 777 ${{ github.workspace }}/reports
      
      - name: Run tests
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/tests
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
        with:
          docker-image: selenium/standalone-chrome:latest
      
      - name: Store test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports

  report:
    if: always()
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: reports
      - name: Output report
        uses: joonvena/robotframework-reporter-action@v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
