name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install webdriver-manager

      - name: Run Robot Framework tests
        working-directory: ./robotframework
        run: robot -d reports tests/

      - name: Store test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: ./robotframework/reports

  report:
    if: always()
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: reports
      - name: Output report
        uses: joonvena/robotframework-reporter-action@v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}