name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install webdriver-manager
          pip install allure-robotframework
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Run Robot Framework tests with Allure listener
        working-directory: ./robotframework
        run: |
          mkdir -p allure-results
          robot --listener allure_robotframework;allure-results tests/
  
      - name: Generate Allure Report
        run: |
          allure generate robotframework/allure-results -o robotframework/allure-report --clean

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: robotframework/allure-report/

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./robotframework/allure-report